### PR TITLE
sets the charset to utf-8 in case ruby fails to load special characters

### PR DESCRIPTION
**Pull request by gercheq**

### CODE REVIEW

**Comment by repires** [comment]
Can I help somehow? Ive been waiting for a good time. lol

**Comment by tarraschk** [comment]
Hi there!

Yes, absolutely, I commented in another discussion thread, but I already pushed the bases of the new UI-Project.

The new branch is dev-ui: https://github.com/tarraschk/TinderAutoLike/tree/dev-ui

I'm actually working on the main page to handle many accounts at the same time.
After that, I'll need to add the UI to edit settings per account (lat/long, common friends or no, etc).
And the next step will be to add a bot with Workers to do that in the BackEnd, asyncronously.

Then, we'll be working on the messaging features :).

What could you guys think you might help on?

**Comment by gercheq** [comment]
Sorry guys, I didn't get a chance to look into UI yet.

Btw, I ran the script twice on my personal account. one with 25 miles radius and like 2500+ people. Then I increased it to 100 miles and liked 6500+ people. In the end I got matched to 10-12 people within the next week. Either my profile is pretty bad or Tinder is blocking these type of mass likes. I recommend putting a random delay between each like.

**Comment by tarraschk** [comment]
This a very interesting comment.
For the random delay, a delay such as "2.5+rand" (going from 2.5s to 3.5s) should be okay.

**Comment by tarraschk** [comment]
Update: had some work to do this week-end, should deliver account management by wednesday.
Stay tuned :)

**Pull request merged**
